name: .NET Build and Schedule

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 * * * *' # Executa a cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restaurar dependências
      run: dotnet restore

    - name: Compilar o projeto
      run: dotnet build --no-restore

    - name: Rodar testes (exemplo de script personalizado)
      run: echo "Nenhum teste ainda, mas o build passou com sucesso!"
